//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalTrace.Language.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JournalTrace.Language.Localization.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity of entries:.
        /// </summary>
        internal static string countall {
            get {
                return ResourceManager.GetString("countall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directories:.
        /// </summary>
        internal static string countdirectories {
            get {
                return ResourceManager.GetString("countdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files:.
        /// </summary>
        internal static string countfiles {
            get {
                return ResourceManager.GetString("countfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oldest entry:.
        /// </summary>
        internal static string countfirst {
            get {
                return ResourceManager.GetString("countfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current file.
        /// </summary>
        internal static string currentfile {
            get {
                return ResourceManager.GetString("currentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Grid.
        /// </summary>
        internal static string datagrid {
            get {
                return ResourceManager.GetString("datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory Tree.
        /// </summary>
        internal static string directorytree {
            get {
                return ResourceManager.GetString("directorytree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive.
        /// </summary>
        internal static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter entry directory.
        /// </summary>
        internal static string enterdir {
            get {
                return ResourceManager.GetString("enterdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show file information.
        /// </summary>
        internal static string entryinfo {
            get {
                return ResourceManager.GetString("entryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File was deleted.
        /// </summary>
        internal static string filedeleted {
            get {
                return ResourceManager.GetString("filedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Identification.
        /// </summary>
        internal static string fileid {
            get {
                return ResourceManager.GetString("fileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive selection.
        /// </summary>
        internal static string formdrive {
            get {
                return ResourceManager.GetString("formdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entry information.
        /// </summary>
        internal static string formentryinfo {
            get {
                return ResourceManager.GetString("formentryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Idea for the project, translated reasons.
        /// </summary>
        internal static string lordyzagatdesc {
            get {
                return ResourceManager.GetString("lordyzagatdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OpenByFileId Win32 API wrapper for C#.
        /// </summary>
        internal static string nolandesc {
            get {
                return ResourceManager.GetString("nolandesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main developer.
        /// </summary>
        internal static string poneidesc {
            get {
                return ResourceManager.GetString("poneidesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reason.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Root.
        /// </summary>
        internal static string root {
            get {
                return ResourceManager.GetString("root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan.
        /// </summary>
        internal static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NTFS UsnJournal Win32 API wrapper for C#.
        /// </summary>
        internal static string skipperdesc {
            get {
                return ResourceManager.GetString("skipperdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program couldn&apos;t create a handle to the selected drive, to query the current journal state..
        /// </summary>
        internal static string statusdesc_1 {
            get {
                return ResourceManager.GetString("statusdesc-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program couldn&apos;t query the current state of the journal. Make sure the selected drive has journaling enabled..
        /// </summary>
        internal static string statusdesc_2 {
            get {
                return ResourceManager.GetString("statusdesc-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program couldn&apos;t call DeviceIoControl properly to return all the journal entries in the drive..
        /// </summary>
        internal static string statusdesc_3 {
            get {
                return ResourceManager.GetString("statusdesc-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program couldn&apos;t resolve file ID&apos;s properly. Is something blocking the program?.
        /// </summary>
        internal static string statusdesc_4 {
            get {
                return ResourceManager.GetString("statusdesc-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program couldn&apos;t parse journal entries correctly. This could be the program&apos;s fault..
        /// </summary>
        internal static string statusdesc_5 {
            get {
                return ResourceManager.GetString("statusdesc-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select the desired drive and start filtering journal entries..
        /// </summary>
        internal static string statusdesc0 {
            get {
                return ResourceManager.GetString("statusdesc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To query the journal, we have to make sure we can create handles to it without problems..
        /// </summary>
        internal static string statusdesc1 {
            get {
                return ResourceManager.GetString("statusdesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We need to query the current state of the journal to get it&apos;s values..
        /// </summary>
        internal static string statusdesc2 {
            get {
                return ResourceManager.GetString("statusdesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calling DeviceIoControl to give us all the entries in the current journal ID..
        /// </summary>
        internal static string statusdesc3 {
            get {
                return ResourceManager.GetString("statusdesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File ID&apos;s aren&apos;t human readable paths, so we need to resolve all the possible ones..
        /// </summary>
        internal static string statusdesc4 {
            get {
                return ResourceManager.GetString("statusdesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parsing all journal entries into classes that we will modify and query later..
        /// </summary>
        internal static string statusdesc5 {
            get {
                return ResourceManager.GetString("statusdesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a layout type to view the collected data. Each will visualize data on a different way..
        /// </summary>
        internal static string statusdesc6 {
            get {
                return ResourceManager.GetString("statusdesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parsing journal entries to rows....
        /// </summary>
        internal static string statusgrid0 {
            get {
                return ResourceManager.GetString("statusgrid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding rows to control....
        /// </summary>
        internal static string statusgrid1 {
            get {
                return ResourceManager.GetString("statusgrid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t get handle to volume..
        /// </summary>
        internal static string statustitle_1 {
            get {
                return ResourceManager.GetString("statustitle-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t get current journal state..
        /// </summary>
        internal static string statustitle_2 {
            get {
                return ResourceManager.GetString("statustitle-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t query journal entries..
        /// </summary>
        internal static string statustitle_3 {
            get {
                return ResourceManager.GetString("statustitle-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t resolve ID&apos;s..
        /// </summary>
        internal static string statustitle_4 {
            get {
                return ResourceManager.GetString("statustitle-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t parse entries..
        /// </summary>
        internal static string statustitle_5 {
            get {
                return ResourceManager.GetString("statustitle-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting input....
        /// </summary>
        internal static string statustitle0 {
            get {
                return ResourceManager.GetString("statustitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting handle to volume....
        /// </summary>
        internal static string statustitle1 {
            get {
                return ResourceManager.GetString("statustitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting current journal state....
        /// </summary>
        internal static string statustitle2 {
            get {
                return ResourceManager.GetString("statustitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Querying journal entries....
        /// </summary>
        internal static string statustitle3 {
            get {
                return ResourceManager.GetString("statustitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolving file ID&apos;s....
        /// </summary>
        internal static string statustitle4 {
            get {
                return ResourceManager.GetString("statustitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parsing entries....
        /// </summary>
        internal static string statustitle5 {
            get {
                return ResourceManager.GetString("statustitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All done!.
        /// </summary>
        internal static string statustitle6 {
            get {
                return ResourceManager.GetString("statustitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total free space.
        /// </summary>
        internal static string totalfreespace {
            get {
                return ResourceManager.GetString("totalfreespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total size.
        /// </summary>
        internal static string totalsize {
            get {
                return ResourceManager.GetString("totalsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data overwrite,Data extend,Data truncation,Named data overwrite,Named data extend,Named data truncation,File create,File delete,EA Change,Security change,Rename: old name,Rename: new name,Indexable change,Basic info change,Hard link change,Compression change,Encryption change,Object ID change,Reparse point change,Stream change,Close.
        /// </summary>
        internal static string usnreasons {
            get {
                return ResourceManager.GetString("usnreasons", resourceCulture);
            }
        }
    }
}
